/*
Jellyfin API

Testing TvShowsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package jellyfin

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/shamelin/go-jellyfin-api-client"
)

func Test_jellyfin_TvShowsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TvShowsAPIService GetEpisodes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var seriesId string

		resp, httpRes, err := apiClient.TvShowsAPI.GetEpisodes(context.Background(), seriesId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TvShowsAPIService GetNextUp", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TvShowsAPI.GetNextUp(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TvShowsAPIService GetSeasons", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var seriesId string

		resp, httpRes, err := apiClient.TvShowsAPI.GetSeasons(context.Background(), seriesId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TvShowsAPIService GetUpcomingEpisodes", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.TvShowsAPI.GetUpcomingEpisodes(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
