/*
Jellyfin API

Testing TrickplayAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package jellyfin

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/shamelin/go-jellyfin-api-client"
)

func Test_jellyfin_TrickplayAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TrickplayAPIService GetTrickplayHlsPlaylist", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var itemId string
		var width int32

		resp, httpRes, err := apiClient.TrickplayAPI.GetTrickplayHlsPlaylist(context.Background(), itemId, width).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TrickplayAPIService GetTrickplayTileImage", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var itemId string
		var width int32
		var index int32

		resp, httpRes, err := apiClient.TrickplayAPI.GetTrickplayTileImage(context.Background(), itemId, width, index).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
