/*
Jellyfin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 10.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jellyfin

import (
	"encoding/json"
)

// checks if the JellyfinActivityLogEntryStartMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JellyfinActivityLogEntryStartMessage{}

// JellyfinActivityLogEntryStartMessage Activity log entry start message.  Data is the timing data encoded as \"$initialDelay,$interval\" in ms.
type JellyfinActivityLogEntryStartMessage struct {
	// Gets or sets the data.
	Data NullableString `json:"Data,omitempty"`
	// The different kinds of messages that are used in the WebSocket api.
	MessageType *JellyfinSessionMessageType `json:"MessageType,omitempty"`
}

// NewJellyfinActivityLogEntryStartMessage instantiates a new JellyfinActivityLogEntryStartMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJellyfinActivityLogEntryStartMessage() *JellyfinActivityLogEntryStartMessage {
	this := JellyfinActivityLogEntryStartMessage{}
	return &this
}

// NewJellyfinActivityLogEntryStartMessageWithDefaults instantiates a new JellyfinActivityLogEntryStartMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJellyfinActivityLogEntryStartMessageWithDefaults() *JellyfinActivityLogEntryStartMessage {
	this := JellyfinActivityLogEntryStartMessage{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinActivityLogEntryStartMessage) GetData() string {
	if o == nil || IsNil(o.Data.Get()) {
		var ret string
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinActivityLogEntryStartMessage) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *JellyfinActivityLogEntryStartMessage) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableString and assigns it to the Data field.
func (o *JellyfinActivityLogEntryStartMessage) SetData(v string) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *JellyfinActivityLogEntryStartMessage) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *JellyfinActivityLogEntryStartMessage) UnsetData() {
	o.Data.Unset()
}

// GetMessageType returns the MessageType field value if set, zero value otherwise.
func (o *JellyfinActivityLogEntryStartMessage) GetMessageType() JellyfinSessionMessageType {
	if o == nil || IsNil(o.MessageType) {
		var ret JellyfinSessionMessageType
		return ret
	}
	return *o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JellyfinActivityLogEntryStartMessage) GetMessageTypeOk() (*JellyfinSessionMessageType, bool) {
	if o == nil || IsNil(o.MessageType) {
		return nil, false
	}
	return o.MessageType, true
}

// HasMessageType returns a boolean if a field has been set.
func (o *JellyfinActivityLogEntryStartMessage) HasMessageType() bool {
	if o != nil && !IsNil(o.MessageType) {
		return true
	}

	return false
}

// SetMessageType gets a reference to the given JellyfinSessionMessageType and assigns it to the MessageType field.
func (o *JellyfinActivityLogEntryStartMessage) SetMessageType(v JellyfinSessionMessageType) {
	o.MessageType = &v
}

func (o JellyfinActivityLogEntryStartMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JellyfinActivityLogEntryStartMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data.IsSet() {
		toSerialize["Data"] = o.Data.Get()
	}
	if !IsNil(o.MessageType) {
		toSerialize["MessageType"] = o.MessageType
	}
	return toSerialize, nil
}

type NullableJellyfinActivityLogEntryStartMessage struct {
	value *JellyfinActivityLogEntryStartMessage
	isSet bool
}

func (v NullableJellyfinActivityLogEntryStartMessage) Get() *JellyfinActivityLogEntryStartMessage {
	return v.value
}

func (v *NullableJellyfinActivityLogEntryStartMessage) Set(val *JellyfinActivityLogEntryStartMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableJellyfinActivityLogEntryStartMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableJellyfinActivityLogEntryStartMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJellyfinActivityLogEntryStartMessage(val *JellyfinActivityLogEntryStartMessage) *NullableJellyfinActivityLogEntryStartMessage {
	return &NullableJellyfinActivityLogEntryStartMessage{value: val, isSet: true}
}

func (v NullableJellyfinActivityLogEntryStartMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJellyfinActivityLogEntryStartMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


