/*
Jellyfin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 10.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jellyfin

import (
	"encoding/json"
)

// checks if the JellyfinPluginInstallationCancelledMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JellyfinPluginInstallationCancelledMessage{}

// JellyfinPluginInstallationCancelledMessage Plugin installation cancelled message.
type JellyfinPluginInstallationCancelledMessage struct {
	// Class InstallationInfo.
	Data NullableJellyfinInstallationInfo `json:"Data,omitempty"`
	// Gets or sets the message id.
	MessageId *string `json:"MessageId,omitempty"`
	// The different kinds of messages that are used in the WebSocket api.
	MessageType *JellyfinSessionMessageType `json:"MessageType,omitempty"`
}

// NewJellyfinPluginInstallationCancelledMessage instantiates a new JellyfinPluginInstallationCancelledMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJellyfinPluginInstallationCancelledMessage() *JellyfinPluginInstallationCancelledMessage {
	this := JellyfinPluginInstallationCancelledMessage{}
	return &this
}

// NewJellyfinPluginInstallationCancelledMessageWithDefaults instantiates a new JellyfinPluginInstallationCancelledMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJellyfinPluginInstallationCancelledMessageWithDefaults() *JellyfinPluginInstallationCancelledMessage {
	this := JellyfinPluginInstallationCancelledMessage{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinPluginInstallationCancelledMessage) GetData() JellyfinInstallationInfo {
	if o == nil || IsNil(o.Data.Get()) {
		var ret JellyfinInstallationInfo
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinPluginInstallationCancelledMessage) GetDataOk() (*JellyfinInstallationInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *JellyfinPluginInstallationCancelledMessage) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableJellyfinInstallationInfo and assigns it to the Data field.
func (o *JellyfinPluginInstallationCancelledMessage) SetData(v JellyfinInstallationInfo) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *JellyfinPluginInstallationCancelledMessage) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *JellyfinPluginInstallationCancelledMessage) UnsetData() {
	o.Data.Unset()
}

// GetMessageId returns the MessageId field value if set, zero value otherwise.
func (o *JellyfinPluginInstallationCancelledMessage) GetMessageId() string {
	if o == nil || IsNil(o.MessageId) {
		var ret string
		return ret
	}
	return *o.MessageId
}

// GetMessageIdOk returns a tuple with the MessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JellyfinPluginInstallationCancelledMessage) GetMessageIdOk() (*string, bool) {
	if o == nil || IsNil(o.MessageId) {
		return nil, false
	}
	return o.MessageId, true
}

// HasMessageId returns a boolean if a field has been set.
func (o *JellyfinPluginInstallationCancelledMessage) HasMessageId() bool {
	if o != nil && !IsNil(o.MessageId) {
		return true
	}

	return false
}

// SetMessageId gets a reference to the given string and assigns it to the MessageId field.
func (o *JellyfinPluginInstallationCancelledMessage) SetMessageId(v string) {
	o.MessageId = &v
}

// GetMessageType returns the MessageType field value if set, zero value otherwise.
func (o *JellyfinPluginInstallationCancelledMessage) GetMessageType() JellyfinSessionMessageType {
	if o == nil || IsNil(o.MessageType) {
		var ret JellyfinSessionMessageType
		return ret
	}
	return *o.MessageType
}

// GetMessageTypeOk returns a tuple with the MessageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JellyfinPluginInstallationCancelledMessage) GetMessageTypeOk() (*JellyfinSessionMessageType, bool) {
	if o == nil || IsNil(o.MessageType) {
		return nil, false
	}
	return o.MessageType, true
}

// HasMessageType returns a boolean if a field has been set.
func (o *JellyfinPluginInstallationCancelledMessage) HasMessageType() bool {
	if o != nil && !IsNil(o.MessageType) {
		return true
	}

	return false
}

// SetMessageType gets a reference to the given JellyfinSessionMessageType and assigns it to the MessageType field.
func (o *JellyfinPluginInstallationCancelledMessage) SetMessageType(v JellyfinSessionMessageType) {
	o.MessageType = &v
}

func (o JellyfinPluginInstallationCancelledMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JellyfinPluginInstallationCancelledMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Data.IsSet() {
		toSerialize["Data"] = o.Data.Get()
	}
	if !IsNil(o.MessageId) {
		toSerialize["MessageId"] = o.MessageId
	}
	if !IsNil(o.MessageType) {
		toSerialize["MessageType"] = o.MessageType
	}
	return toSerialize, nil
}

type NullableJellyfinPluginInstallationCancelledMessage struct {
	value *JellyfinPluginInstallationCancelledMessage
	isSet bool
}

func (v NullableJellyfinPluginInstallationCancelledMessage) Get() *JellyfinPluginInstallationCancelledMessage {
	return v.value
}

func (v *NullableJellyfinPluginInstallationCancelledMessage) Set(val *JellyfinPluginInstallationCancelledMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableJellyfinPluginInstallationCancelledMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableJellyfinPluginInstallationCancelledMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJellyfinPluginInstallationCancelledMessage(val *JellyfinPluginInstallationCancelledMessage) *NullableJellyfinPluginInstallationCancelledMessage {
	return &NullableJellyfinPluginInstallationCancelledMessage{value: val, isSet: true}
}

func (v NullableJellyfinPluginInstallationCancelledMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJellyfinPluginInstallationCancelledMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


