/*
Jellyfin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 10.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jellyfin

import (
	"encoding/json"
	"time"
)

// checks if the JellyfinUpdateUserItemDataDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JellyfinUpdateUserItemDataDto{}

// JellyfinUpdateUserItemDataDto This is used by the api to get information about a item user data.
type JellyfinUpdateUserItemDataDto struct {
	// Gets or sets the rating.
	Rating NullableFloat64 `json:"Rating,omitempty"`
	// Gets or sets the played percentage.
	PlayedPercentage NullableFloat64 `json:"PlayedPercentage,omitempty"`
	// Gets or sets the unplayed item count.
	UnplayedItemCount NullableInt32 `json:"UnplayedItemCount,omitempty"`
	// Gets or sets the playback position ticks.
	PlaybackPositionTicks NullableInt64 `json:"PlaybackPositionTicks,omitempty"`
	// Gets or sets the play count.
	PlayCount NullableInt32 `json:"PlayCount,omitempty"`
	// Gets or sets a value indicating whether this instance is favorite.
	IsFavorite NullableBool `json:"IsFavorite,omitempty"`
	// Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UpdateUserItemDataDto is likes.
	Likes NullableBool `json:"Likes,omitempty"`
	// Gets or sets the last played date.
	LastPlayedDate NullableTime `json:"LastPlayedDate,omitempty"`
	// Gets or sets a value indicating whether this MediaBrowser.Model.Dto.UserItemDataDto is played.
	Played NullableBool `json:"Played,omitempty"`
	// Gets or sets the key.
	Key NullableString `json:"Key,omitempty"`
	// Gets or sets the item identifier.
	ItemId NullableString `json:"ItemId,omitempty"`
}

// NewJellyfinUpdateUserItemDataDto instantiates a new JellyfinUpdateUserItemDataDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJellyfinUpdateUserItemDataDto() *JellyfinUpdateUserItemDataDto {
	this := JellyfinUpdateUserItemDataDto{}
	return &this
}

// NewJellyfinUpdateUserItemDataDtoWithDefaults instantiates a new JellyfinUpdateUserItemDataDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJellyfinUpdateUserItemDataDtoWithDefaults() *JellyfinUpdateUserItemDataDto {
	this := JellyfinUpdateUserItemDataDto{}
	return &this
}

// GetRating returns the Rating field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetRating() float64 {
	if o == nil || IsNil(o.Rating.Get()) {
		var ret float64
		return ret
	}
	return *o.Rating.Get()
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetRatingOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rating.Get(), o.Rating.IsSet()
}

// HasRating returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasRating() bool {
	if o != nil && o.Rating.IsSet() {
		return true
	}

	return false
}

// SetRating gets a reference to the given NullableFloat64 and assigns it to the Rating field.
func (o *JellyfinUpdateUserItemDataDto) SetRating(v float64) {
	o.Rating.Set(&v)
}
// SetRatingNil sets the value for Rating to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetRatingNil() {
	o.Rating.Set(nil)
}

// UnsetRating ensures that no value is present for Rating, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetRating() {
	o.Rating.Unset()
}

// GetPlayedPercentage returns the PlayedPercentage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetPlayedPercentage() float64 {
	if o == nil || IsNil(o.PlayedPercentage.Get()) {
		var ret float64
		return ret
	}
	return *o.PlayedPercentage.Get()
}

// GetPlayedPercentageOk returns a tuple with the PlayedPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetPlayedPercentageOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlayedPercentage.Get(), o.PlayedPercentage.IsSet()
}

// HasPlayedPercentage returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasPlayedPercentage() bool {
	if o != nil && o.PlayedPercentage.IsSet() {
		return true
	}

	return false
}

// SetPlayedPercentage gets a reference to the given NullableFloat64 and assigns it to the PlayedPercentage field.
func (o *JellyfinUpdateUserItemDataDto) SetPlayedPercentage(v float64) {
	o.PlayedPercentage.Set(&v)
}
// SetPlayedPercentageNil sets the value for PlayedPercentage to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetPlayedPercentageNil() {
	o.PlayedPercentage.Set(nil)
}

// UnsetPlayedPercentage ensures that no value is present for PlayedPercentage, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetPlayedPercentage() {
	o.PlayedPercentage.Unset()
}

// GetUnplayedItemCount returns the UnplayedItemCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetUnplayedItemCount() int32 {
	if o == nil || IsNil(o.UnplayedItemCount.Get()) {
		var ret int32
		return ret
	}
	return *o.UnplayedItemCount.Get()
}

// GetUnplayedItemCountOk returns a tuple with the UnplayedItemCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetUnplayedItemCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnplayedItemCount.Get(), o.UnplayedItemCount.IsSet()
}

// HasUnplayedItemCount returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasUnplayedItemCount() bool {
	if o != nil && o.UnplayedItemCount.IsSet() {
		return true
	}

	return false
}

// SetUnplayedItemCount gets a reference to the given NullableInt32 and assigns it to the UnplayedItemCount field.
func (o *JellyfinUpdateUserItemDataDto) SetUnplayedItemCount(v int32) {
	o.UnplayedItemCount.Set(&v)
}
// SetUnplayedItemCountNil sets the value for UnplayedItemCount to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetUnplayedItemCountNil() {
	o.UnplayedItemCount.Set(nil)
}

// UnsetUnplayedItemCount ensures that no value is present for UnplayedItemCount, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetUnplayedItemCount() {
	o.UnplayedItemCount.Unset()
}

// GetPlaybackPositionTicks returns the PlaybackPositionTicks field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetPlaybackPositionTicks() int64 {
	if o == nil || IsNil(o.PlaybackPositionTicks.Get()) {
		var ret int64
		return ret
	}
	return *o.PlaybackPositionTicks.Get()
}

// GetPlaybackPositionTicksOk returns a tuple with the PlaybackPositionTicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetPlaybackPositionTicksOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlaybackPositionTicks.Get(), o.PlaybackPositionTicks.IsSet()
}

// HasPlaybackPositionTicks returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasPlaybackPositionTicks() bool {
	if o != nil && o.PlaybackPositionTicks.IsSet() {
		return true
	}

	return false
}

// SetPlaybackPositionTicks gets a reference to the given NullableInt64 and assigns it to the PlaybackPositionTicks field.
func (o *JellyfinUpdateUserItemDataDto) SetPlaybackPositionTicks(v int64) {
	o.PlaybackPositionTicks.Set(&v)
}
// SetPlaybackPositionTicksNil sets the value for PlaybackPositionTicks to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetPlaybackPositionTicksNil() {
	o.PlaybackPositionTicks.Set(nil)
}

// UnsetPlaybackPositionTicks ensures that no value is present for PlaybackPositionTicks, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetPlaybackPositionTicks() {
	o.PlaybackPositionTicks.Unset()
}

// GetPlayCount returns the PlayCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetPlayCount() int32 {
	if o == nil || IsNil(o.PlayCount.Get()) {
		var ret int32
		return ret
	}
	return *o.PlayCount.Get()
}

// GetPlayCountOk returns a tuple with the PlayCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetPlayCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlayCount.Get(), o.PlayCount.IsSet()
}

// HasPlayCount returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasPlayCount() bool {
	if o != nil && o.PlayCount.IsSet() {
		return true
	}

	return false
}

// SetPlayCount gets a reference to the given NullableInt32 and assigns it to the PlayCount field.
func (o *JellyfinUpdateUserItemDataDto) SetPlayCount(v int32) {
	o.PlayCount.Set(&v)
}
// SetPlayCountNil sets the value for PlayCount to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetPlayCountNil() {
	o.PlayCount.Set(nil)
}

// UnsetPlayCount ensures that no value is present for PlayCount, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetPlayCount() {
	o.PlayCount.Unset()
}

// GetIsFavorite returns the IsFavorite field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetIsFavorite() bool {
	if o == nil || IsNil(o.IsFavorite.Get()) {
		var ret bool
		return ret
	}
	return *o.IsFavorite.Get()
}

// GetIsFavoriteOk returns a tuple with the IsFavorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetIsFavoriteOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsFavorite.Get(), o.IsFavorite.IsSet()
}

// HasIsFavorite returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasIsFavorite() bool {
	if o != nil && o.IsFavorite.IsSet() {
		return true
	}

	return false
}

// SetIsFavorite gets a reference to the given NullableBool and assigns it to the IsFavorite field.
func (o *JellyfinUpdateUserItemDataDto) SetIsFavorite(v bool) {
	o.IsFavorite.Set(&v)
}
// SetIsFavoriteNil sets the value for IsFavorite to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetIsFavoriteNil() {
	o.IsFavorite.Set(nil)
}

// UnsetIsFavorite ensures that no value is present for IsFavorite, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetIsFavorite() {
	o.IsFavorite.Unset()
}

// GetLikes returns the Likes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetLikes() bool {
	if o == nil || IsNil(o.Likes.Get()) {
		var ret bool
		return ret
	}
	return *o.Likes.Get()
}

// GetLikesOk returns a tuple with the Likes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetLikesOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Likes.Get(), o.Likes.IsSet()
}

// HasLikes returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasLikes() bool {
	if o != nil && o.Likes.IsSet() {
		return true
	}

	return false
}

// SetLikes gets a reference to the given NullableBool and assigns it to the Likes field.
func (o *JellyfinUpdateUserItemDataDto) SetLikes(v bool) {
	o.Likes.Set(&v)
}
// SetLikesNil sets the value for Likes to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetLikesNil() {
	o.Likes.Set(nil)
}

// UnsetLikes ensures that no value is present for Likes, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetLikes() {
	o.Likes.Unset()
}

// GetLastPlayedDate returns the LastPlayedDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetLastPlayedDate() time.Time {
	if o == nil || IsNil(o.LastPlayedDate.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastPlayedDate.Get()
}

// GetLastPlayedDateOk returns a tuple with the LastPlayedDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetLastPlayedDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastPlayedDate.Get(), o.LastPlayedDate.IsSet()
}

// HasLastPlayedDate returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasLastPlayedDate() bool {
	if o != nil && o.LastPlayedDate.IsSet() {
		return true
	}

	return false
}

// SetLastPlayedDate gets a reference to the given NullableTime and assigns it to the LastPlayedDate field.
func (o *JellyfinUpdateUserItemDataDto) SetLastPlayedDate(v time.Time) {
	o.LastPlayedDate.Set(&v)
}
// SetLastPlayedDateNil sets the value for LastPlayedDate to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetLastPlayedDateNil() {
	o.LastPlayedDate.Set(nil)
}

// UnsetLastPlayedDate ensures that no value is present for LastPlayedDate, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetLastPlayedDate() {
	o.LastPlayedDate.Unset()
}

// GetPlayed returns the Played field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetPlayed() bool {
	if o == nil || IsNil(o.Played.Get()) {
		var ret bool
		return ret
	}
	return *o.Played.Get()
}

// GetPlayedOk returns a tuple with the Played field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetPlayedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Played.Get(), o.Played.IsSet()
}

// HasPlayed returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasPlayed() bool {
	if o != nil && o.Played.IsSet() {
		return true
	}

	return false
}

// SetPlayed gets a reference to the given NullableBool and assigns it to the Played field.
func (o *JellyfinUpdateUserItemDataDto) SetPlayed(v bool) {
	o.Played.Set(&v)
}
// SetPlayedNil sets the value for Played to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetPlayedNil() {
	o.Played.Set(nil)
}

// UnsetPlayed ensures that no value is present for Played, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetPlayed() {
	o.Played.Unset()
}

// GetKey returns the Key field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetKey() string {
	if o == nil || IsNil(o.Key.Get()) {
		var ret string
		return ret
	}
	return *o.Key.Get()
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Key.Get(), o.Key.IsSet()
}

// HasKey returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasKey() bool {
	if o != nil && o.Key.IsSet() {
		return true
	}

	return false
}

// SetKey gets a reference to the given NullableString and assigns it to the Key field.
func (o *JellyfinUpdateUserItemDataDto) SetKey(v string) {
	o.Key.Set(&v)
}
// SetKeyNil sets the value for Key to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetKeyNil() {
	o.Key.Set(nil)
}

// UnsetKey ensures that no value is present for Key, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetKey() {
	o.Key.Unset()
}

// GetItemId returns the ItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *JellyfinUpdateUserItemDataDto) GetItemId() string {
	if o == nil || IsNil(o.ItemId.Get()) {
		var ret string
		return ret
	}
	return *o.ItemId.Get()
}

// GetItemIdOk returns a tuple with the ItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *JellyfinUpdateUserItemDataDto) GetItemIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ItemId.Get(), o.ItemId.IsSet()
}

// HasItemId returns a boolean if a field has been set.
func (o *JellyfinUpdateUserItemDataDto) HasItemId() bool {
	if o != nil && o.ItemId.IsSet() {
		return true
	}

	return false
}

// SetItemId gets a reference to the given NullableString and assigns it to the ItemId field.
func (o *JellyfinUpdateUserItemDataDto) SetItemId(v string) {
	o.ItemId.Set(&v)
}
// SetItemIdNil sets the value for ItemId to be an explicit nil
func (o *JellyfinUpdateUserItemDataDto) SetItemIdNil() {
	o.ItemId.Set(nil)
}

// UnsetItemId ensures that no value is present for ItemId, not even an explicit nil
func (o *JellyfinUpdateUserItemDataDto) UnsetItemId() {
	o.ItemId.Unset()
}

func (o JellyfinUpdateUserItemDataDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JellyfinUpdateUserItemDataDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Rating.IsSet() {
		toSerialize["Rating"] = o.Rating.Get()
	}
	if o.PlayedPercentage.IsSet() {
		toSerialize["PlayedPercentage"] = o.PlayedPercentage.Get()
	}
	if o.UnplayedItemCount.IsSet() {
		toSerialize["UnplayedItemCount"] = o.UnplayedItemCount.Get()
	}
	if o.PlaybackPositionTicks.IsSet() {
		toSerialize["PlaybackPositionTicks"] = o.PlaybackPositionTicks.Get()
	}
	if o.PlayCount.IsSet() {
		toSerialize["PlayCount"] = o.PlayCount.Get()
	}
	if o.IsFavorite.IsSet() {
		toSerialize["IsFavorite"] = o.IsFavorite.Get()
	}
	if o.Likes.IsSet() {
		toSerialize["Likes"] = o.Likes.Get()
	}
	if o.LastPlayedDate.IsSet() {
		toSerialize["LastPlayedDate"] = o.LastPlayedDate.Get()
	}
	if o.Played.IsSet() {
		toSerialize["Played"] = o.Played.Get()
	}
	if o.Key.IsSet() {
		toSerialize["Key"] = o.Key.Get()
	}
	if o.ItemId.IsSet() {
		toSerialize["ItemId"] = o.ItemId.Get()
	}
	return toSerialize, nil
}

type NullableJellyfinUpdateUserItemDataDto struct {
	value *JellyfinUpdateUserItemDataDto
	isSet bool
}

func (v NullableJellyfinUpdateUserItemDataDto) Get() *JellyfinUpdateUserItemDataDto {
	return v.value
}

func (v *NullableJellyfinUpdateUserItemDataDto) Set(val *JellyfinUpdateUserItemDataDto) {
	v.value = val
	v.isSet = true
}

func (v NullableJellyfinUpdateUserItemDataDto) IsSet() bool {
	return v.isSet
}

func (v *NullableJellyfinUpdateUserItemDataDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJellyfinUpdateUserItemDataDto(val *JellyfinUpdateUserItemDataDto) *NullableJellyfinUpdateUserItemDataDto {
	return &NullableJellyfinUpdateUserItemDataDto{value: val, isSet: true}
}

func (v NullableJellyfinUpdateUserItemDataDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJellyfinUpdateUserItemDataDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


