/*
Jellyfin API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 10.10.2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package jellyfin

import (
	"encoding/json"
)

// checks if the JellyfinSetPlaylistItemRequestDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JellyfinSetPlaylistItemRequestDto{}

// JellyfinSetPlaylistItemRequestDto Class SetPlaylistItemRequestDto.
type JellyfinSetPlaylistItemRequestDto struct {
	// Gets or sets the playlist identifier of the playing item.
	PlaylistItemId *string `json:"PlaylistItemId,omitempty"`
}

// NewJellyfinSetPlaylistItemRequestDto instantiates a new JellyfinSetPlaylistItemRequestDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJellyfinSetPlaylistItemRequestDto() *JellyfinSetPlaylistItemRequestDto {
	this := JellyfinSetPlaylistItemRequestDto{}
	return &this
}

// NewJellyfinSetPlaylistItemRequestDtoWithDefaults instantiates a new JellyfinSetPlaylistItemRequestDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJellyfinSetPlaylistItemRequestDtoWithDefaults() *JellyfinSetPlaylistItemRequestDto {
	this := JellyfinSetPlaylistItemRequestDto{}
	return &this
}

// GetPlaylistItemId returns the PlaylistItemId field value if set, zero value otherwise.
func (o *JellyfinSetPlaylistItemRequestDto) GetPlaylistItemId() string {
	if o == nil || IsNil(o.PlaylistItemId) {
		var ret string
		return ret
	}
	return *o.PlaylistItemId
}

// GetPlaylistItemIdOk returns a tuple with the PlaylistItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JellyfinSetPlaylistItemRequestDto) GetPlaylistItemIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlaylistItemId) {
		return nil, false
	}
	return o.PlaylistItemId, true
}

// HasPlaylistItemId returns a boolean if a field has been set.
func (o *JellyfinSetPlaylistItemRequestDto) HasPlaylistItemId() bool {
	if o != nil && !IsNil(o.PlaylistItemId) {
		return true
	}

	return false
}

// SetPlaylistItemId gets a reference to the given string and assigns it to the PlaylistItemId field.
func (o *JellyfinSetPlaylistItemRequestDto) SetPlaylistItemId(v string) {
	o.PlaylistItemId = &v
}

func (o JellyfinSetPlaylistItemRequestDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JellyfinSetPlaylistItemRequestDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PlaylistItemId) {
		toSerialize["PlaylistItemId"] = o.PlaylistItemId
	}
	return toSerialize, nil
}

type NullableJellyfinSetPlaylistItemRequestDto struct {
	value *JellyfinSetPlaylistItemRequestDto
	isSet bool
}

func (v NullableJellyfinSetPlaylistItemRequestDto) Get() *JellyfinSetPlaylistItemRequestDto {
	return v.value
}

func (v *NullableJellyfinSetPlaylistItemRequestDto) Set(val *JellyfinSetPlaylistItemRequestDto) {
	v.value = val
	v.isSet = true
}

func (v NullableJellyfinSetPlaylistItemRequestDto) IsSet() bool {
	return v.isSet
}

func (v *NullableJellyfinSetPlaylistItemRequestDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJellyfinSetPlaylistItemRequestDto(val *JellyfinSetPlaylistItemRequestDto) *NullableJellyfinSetPlaylistItemRequestDto {
	return &NullableJellyfinSetPlaylistItemRequestDto{value: val, isSet: true}
}

func (v NullableJellyfinSetPlaylistItemRequestDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJellyfinSetPlaylistItemRequestDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


